//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSModCreator.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NSModCreator.Localizations.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takyon&apos;s Mod Creator.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string BrowseButton {
            get {
                return ResourceManager.GetString("BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string ClearButton {
            get {
                return ResourceManager.GetString("ClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string CreateTab {
            get {
                return ResourceManager.GetString("CreateTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For help hover over the labels.
        /// </summary>
        internal static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Path.
        /// </summary>
        internal static string IconPath {
            get {
                return ResourceManager.GetString("IconPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Folder.
        /// </summary>
        internal static string InstallFolder {
            get {
                return ResourceManager.GetString("InstallFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LangButton {
            get {
                return ResourceManager.GetString("LangButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Priority.
        /// </summary>
        internal static string LoadPriority {
            get {
                return ResourceManager.GetString("LoadPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        internal static string ModDependencies {
            get {
                return ResourceManager.GetString("ModDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ModDescriptionLabel {
            get {
                return ResourceManager.GetString("ModDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a very cool mod that only does cool stuff.
        /// </summary>
        internal static string ModDescWatermark {
            get {
                return ResourceManager.GetString("ModDescWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Folder.
        /// </summary>
        internal static string ModFolder {
            get {
                return ResourceManager.GetString("ModFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Name.
        /// </summary>
        internal static string ModName {
            get {
                return ResourceManager.GetString("ModName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YourName.ModName.
        /// </summary>
        internal static string ModNameWatermark {
            get {
                return ResourceManager.GetString("ModNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Folder.
        /// </summary>
        internal static string OutputFolder {
            get {
                return ResourceManager.GetString("OutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        internal static string PublishTab {
            get {
                return ResourceManager.GetString("PublishTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredOnClient.
        /// </summary>
        internal static string RequiredOnClient {
            get {
                return ResourceManager.GetString("RequiredOnClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run on.
        /// </summary>
        internal static string RunOn {
            get {
                return ResourceManager.GetString("RunOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the mod icon. 256x256 and PNG.
        /// </summary>
        internal static string ToolTipIconPath {
            get {
                return ResourceManager.GetString("ToolTipIconPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path where the mod will be installed.
        /// </summary>
        internal static string ToolTipInstallFolder {
            get {
                return ResourceManager.GetString("ToolTipInstallFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doesn&apos;t matter for most projects and can be left default. May be the reason for mods conflicting however.
        /// </summary>
        internal static string ToolTipLoadPriority {
            get {
                return ResourceManager.GetString("ToolTipLoadPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the mod you want to release.
        /// </summary>
        internal static string ToolTipModFolder {
            get {
                return ResourceManager.GetString("ToolTipModFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path where the release will be stored.
        /// </summary>
        internal static string ToolTipOutputFolder {
            get {
                return ResourceManager.GetString("ToolTipOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether or not your mod is required on Client. True for mods that modify client files, false for server only.
        /// </summary>
        internal static string ToolTipRequiredOnClient {
            get {
                return ResourceManager.GetString("ToolTipRequiredOnClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depends on where your scripts are going to run.
        /// </summary>
        internal static string ToolTipRunOn {
            get {
                return ResourceManager.GetString("ToolTipRunOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
